# Sample and Phenotype Sheets 
# !!! Required !!!
samples: ../config/arabidopsis_samples.tsv
phenotypes: ../config/arabidopsis_phenos.tsv

# =================================================================================================
#     Reference Genome
# =================================================================================================

ref:
  # !!! Reference genome in Fasta format required for the alignment step !!!
  fasta: /scratch/ac32082/kGWASflow/.test/arabidopsis_data/ref/TAIR10_chr_all.fa
  

# =================================================================================================
#     Workflow Settings
# =================================================================================================

settings:

  trimming: 
    # Set to true in order to perform addapter trimming on raw reads
    activate: false

  kmers_gwas:
    # TODO Convert kmers table to PLINK 
    # PLINK-conversion:
    # # Set to true in order to convert k-mers table to PLINK format (.bed)
    #   activate: false

    use_kmers_kinship:
      activate: true
    # This will be ignored if use_kmers is activated
    use_snps:
      # This will be ignored if use_kmers is activated
      activate: false
      # If activated, you need to provide a SNP table in PLINKformat (.bed).
      # PLINK .bed format: https://www.cog-genomics.org/plink/1.9/formats#bed
      ## !!! The order of the samples in SNP table has to be the same as in the samples sheet (samples.tsv file) !!!
      snps_plink_file: ""

# =================================================================================================
#     Resoruces
# =================================================================================================

resources:
  kmers_gwas:
    
# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:

  # ----------------------------------------------------------------------
  #     FastQC Params
  # ----------------------------------------------------------------------

  fastqc:
    # Additional parameters for fastqc
    extra: ""

    # Number of threads for fastqc
    threads: 20

  # ----------------------------------------------------------------------
  #     MultiQC Params
  # ----------------------------------------------------------------------

  multiqc: ""

  # ----------------------------------------------------------------------
  #     cutadapt Params
  # ----------------------------------------------------------------------
  cutadapt:
    # Number of threads for cutadapt
    threads: 36

    # See cutadapt manual:
    # https://cutadapt.readthedocs.io/en/stable/guide.html
    # Set params for single end files
    se:
      adapters: ""
      extra: ""
    # Set params for paired end files
    # https://cutadapt.readthedocs.io/en/stable/guide.html
    pe:
      adapters: ""
      extra: ""
      
  # ----------------------------------------------------------------------
  #     KMC Params
  # ----------------------------------------------------------------------

  kmc:
    threads: 30
    
    # k-mer length (should be between 15-31)
    kmer_len: 31
    
    # Threshold for counted k-mers. For example if 
    # it is 2, k-mer has to appear at least 2 times to be
    # counted. This parameter depends on the coverage, but should be
    # the same for all the individuals.
    count_thresh: 2

    extra: ""

  # ----------------------------------------------------------------------
  #     kmersGWAS Params
  # ----------------------------------------------------------------------

  kmers_gwas:
    # Number of threads to use
    threads: 30

    # Minimum percent of appearance in each strand form
    min_percent_app: 0.2

    # Minor allele count (min allowed appearance of a k-mer) 
    # (Default is: 5)
    minor_allele_count: 5
    
    # Minor allele frequency 
    # (Default is: 0.05)
    minor_allele_freq: 0.05
    
    # Maximal number of variants in each PLINK bed file
    max_num_var: 10000000

    # Number of k-mers to filter from first step 
    # (Default is: 10001)
    kmers_number: 10001

    # Number of permutations to define the threshold 
    # (at least 20 recommended, Default is: 100)
    n_permutations: 100

    # Number of snps to filter from the first step 
    # (Default is: 10001)
    snps_num: 10001

    ## Min number of data points (samples) allowed 
    # (Default is: 30)
    min_data_points: 30

    extra: ""

  # ----------------------------------------------------------------------
  #     results_table Params
  # ----------------------------------------------------------------------

  results_table:
    ## Add "--use_10_per" here if you want to 
    # get summary table from the kmersGWAS results 
    # with 10 percent threshold
    extra: ""

  # ----------------------------------------------------------------------
  #     fetch_kmers Params
  # ----------------------------------------------------------------------

  fetch_kmers:
    threshold: 5

  # ----------------------------------------------------------------------
  #     align_reads Params
  # ----------------------------------------------------------------------
  
  align_reads:
    threads: 30

  # ----------------------------------------------------------------------
  #     bowtie2 Params
  # ----------------------------------------------------------------------

  bowtie2:
    threads: 30
  
    