# Samples Sheets
samples: ../config/samples.tsv

# =================================================================================================
#     Workflow Settings
# =================================================================================================

settings:

  trimming: 
    activate: false

# =================================================================================================
#     Tool Parameters
# =================================================================================================

resources:
  kmers_gwas: 


# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:

  # ----------------------------------------------------------------------
  #     FastQC Params
  # ----------------------------------------------------------------------

  fastqc:
    # Additional parameters for fastqc
    extra: ""

    # Number of threads for fastqc
    threads: 20

  # ----------------------------------------------------------------------
  #     MultiQC Params
  # ----------------------------------------------------------------------

  multiqc: ""

  # ----------------------------------------------------------------------
  #     cutadapt Params
  # ----------------------------------------------------------------------
  cutadapt:
    # Number of threads for cutadapt
    threads: 36

    # See cutadapt manual:
    # https://cutadapt.readthedocs.io/en/stable/guide.html
    # Set params for single end files
    se:
      adapters: ""
      extra: ""
    # Set params for paired end files
    # https://cutadapt.readthedocs.io/en/stable/guide.html
    pe:
      adapters: ""
      extra: ""
      
# ----------------------------------------------------------------------
  #     kmc
  # ----------------------------------------------------------------------

  kmc:
    threads: 30
    
    # k-mer length (should be between 15-31)
    kmer_len: 31
    
    # Threshold for counted k-mers. For example if 
    # it is 2, k-mer has to appear at least 2 times to be
    # counted. This parameter depends on the coverage, but should be
    # the same for all the individuals.
    count_thresh: 2

    extra: ""